version: '3.8'
# our containers <services> 
services: 
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm run dev"
    restart: always
    ports:
      - 6060:6060
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    environment:
      - PORT=6060
      - HOST=127.0.0.1
      - MONGO_URI=mongodb://localhost:27020/grocipe
    networks:
      - grocipe-net 


  mongodb: 
    image: mongo
    volumes: 
      - grocipeApp:/var/lib/mongo
    ports:
      - 2217:2217
    networks:
     - grocipe-net   

networks:
 grocipe-net:
   driver: bridge

volumes: 
  grocipeApp:

    